### ISSUE TITLE
bower packaging

### ISSUE THREAD

**Issue by saadfarooq** [dtinth/synchroscope#1]
Really useful library. It would be great if this was packaged to use with bower.

**Comment by dtinth** [comment]
Hello,

Even without a `bower.json` file, synchroscope is already usable with Bower. Just `bower install dtinth/synchroscope`.

And then simply `<script src="bower_components/synchroscope/client/sync.js"></script>`.

Anyway, pull requests for `bower.json` are welcome. :smile:
