### ISSUE TITLE
Using with the controllerAs syntax

### ISSUE THREAD

**Issue by swinston1000** [dtinth/synchroscope#2]
I'm using the controllerAs syntax for angular and have tried the following code which is not working

```js
 _thisCtrl = this;
_thisCtrl.todos = {...};
var keys = ['todos']
$ync(this, keys, 'myRoom')

```

My browser is throwing an error:

sync.js:163 : Uncaught TypeError: scope.$apply is not a function(…)

Any ideas how to resolve this so I can use your amazing package!
Thanks so much

**Comment by dtinth** [comment]
Hello, sorry I am not using Angular anymore so this project becomes unmaintained.

According to [this article](https://daveceddia.com/convert-scope-to-controlleras/) I think you still need to use `$sync` with `$scope`, prepending it with the name you’ve given to `ng-controller`.

**Comment by swinston1000** [comment]
ok, many thanks!
